// AUTO-GENERATED static Verse of the Day cycle (365 days).
// Admins can override any entry from the admin dashboard.

export type VotdSummaries = {
  guiltInnocence: string;
  shameHonour: string;
  fearPower: string;
};

export type VotdEntry = {
  dayOfYear: number;
  reference: string;
  excerpt: string;
  summaries?: VotdSummaries;
};

// Generic fallback summaries used when no admin override exists for a verse.
// Static text — no runtime AI calls. Admin can edit per verse.
export const DEFAULT_SUMMARIES: VotdSummaries = {
  guiltInnocence:
    "Read through a moral-legal lens: this verse speaks to right standing, conscience, and the assurance of being forgiven and declared just.",
  shameHonour:
    "Read through a relational lens: this verse speaks to belonging, dignity, and the restoration of honour within God's family.",
  fearPower:
    "Read through a spiritual lens: this verse speaks to protection, deliverance, and the power of God over every unseen force.",
};

export const DEFAULT_VOTD: VotdEntry[] = [
  { dayOfYear: 1, reference: "Jeremiah 29:11", excerpt: "For I know the plans I have for you, plans to prosper you and not to harm you, plans to give you hope and a future." },
  { dayOfYear: 2, reference: "Philippians 4:13", excerpt: "I can do all things through Christ who strengthens me." },
  { dayOfYear: 3, reference: "Psalm 23:1", excerpt: "The Lord is my shepherd; I shall not want." },
  { dayOfYear: 4, reference: "Romans 8:28", excerpt: "All things work together for good to those who love God." },
  { dayOfYear: 5, reference: "Isaiah 41:10", excerpt: "Fear not, for I am with you; be not dismayed, for I am your God." },
  { dayOfYear: 6, reference: "Proverbs 3:5", excerpt: "Trust in the Lord with all your heart, and lean not on your own understanding." },
  { dayOfYear: 7, reference: "John 3:16", excerpt: "For God so loved the world that he gave his only Son." },
  { dayOfYear: 8, reference: "Psalm 46:1", excerpt: "God is our refuge and strength, an ever-present help in trouble." },
  { dayOfYear: 9, reference: "Matthew 11:28", excerpt: "Come to me, all you who are weary and burdened, and I will give you rest." },
  { dayOfYear: 10, reference: "Joshua 1:9", excerpt: "Be strong and courageous. Do not be afraid; the Lord your God is with you." },
  { dayOfYear: 11, reference: "2 Corinthians 5:17", excerpt: "If anyone is in Christ, he is a new creation; the old has gone, the new has come." },
  { dayOfYear: 12, reference: "Psalm 27:1", excerpt: "The Lord is my light and my salvation—whom shall I fear?" },
  { dayOfYear: 13, reference: "Isaiah 40:31", excerpt: "Those who hope in the Lord will renew their strength." },
  { dayOfYear: 14, reference: "Romans 12:2", excerpt: "Do not conform to the pattern of this world, but be transformed." },
  { dayOfYear: 15, reference: "Galatians 5:22", excerpt: "The fruit of the Spirit is love, joy, peace, patience, kindness." },
  { dayOfYear: 16, reference: "Ephesians 2:8", excerpt: "For it is by grace you have been saved, through faith." },
  { dayOfYear: 17, reference: "Hebrews 11:1", excerpt: "Faith is confidence in what we hope for and assurance about what we do not see." },
  { dayOfYear: 18, reference: "1 Corinthians 13:4", excerpt: "Love is patient, love is kind. It does not envy, it does not boast." },
  { dayOfYear: 19, reference: "Psalm 119:105", excerpt: "Your word is a lamp for my feet, a light on my path." },
  { dayOfYear: 20, reference: "Matthew 6:33", excerpt: "Seek first the kingdom of God and his righteousness." },
  { dayOfYear: 21, reference: "Proverbs 16:3", excerpt: "Commit to the Lord whatever you do, and he will establish your plans." },
  { dayOfYear: 22, reference: "Psalm 37:4", excerpt: "Delight yourself in the Lord, and he will give you the desires of your heart." },
  { dayOfYear: 23, reference: "Romans 15:13", excerpt: "May the God of hope fill you with all joy and peace as you trust in him." },
  { dayOfYear: 24, reference: "Lamentations 3:22", excerpt: "Because of the Lord's great love we are not consumed; his mercies never fail." },
  { dayOfYear: 25, reference: "Zephaniah 3:17", excerpt: "The Lord your God is with you, the Mighty Warrior who saves." },
  { dayOfYear: 26, reference: "Psalm 34:18", excerpt: "The Lord is close to the brokenhearted and saves those crushed in spirit." },
  { dayOfYear: 27, reference: "1 Peter 5:7", excerpt: "Cast all your anxiety on him because he cares for you." },
  { dayOfYear: 28, reference: "John 14:27", excerpt: "Peace I leave with you; my peace I give you." },
  { dayOfYear: 29, reference: "Philippians 4:6", excerpt: "Do not be anxious about anything, but in every situation present your requests to God." },
  { dayOfYear: 30, reference: "Philippians 4:7", excerpt: "And the peace of God, which transcends all understanding, will guard your hearts." },
  { dayOfYear: 31, reference: "Matthew 5:16", excerpt: "Let your light shine before others, that they may see your good deeds." },
  { dayOfYear: 32, reference: "2 Timothy 1:7", excerpt: "God has not given us a spirit of fear, but of power and of love and of a sound mind." },
  { dayOfYear: 33, reference: "Romans 5:8", excerpt: "But God demonstrates his own love for us in this: While we were still sinners, Christ died for us." },
  { dayOfYear: 34, reference: "John 8:12", excerpt: "I am the light of the world. Whoever follows me will never walk in darkness." },
  { dayOfYear: 35, reference: "Psalm 139:14", excerpt: "I praise you because I am fearfully and wonderfully made." },
  { dayOfYear: 36, reference: "Isaiah 26:3", excerpt: "You will keep in perfect peace those whose minds are steadfast." },
  { dayOfYear: 37, reference: "Romans 10:9", excerpt: "If you declare with your mouth, 'Jesus is Lord,' you will be saved." },
  { dayOfYear: 38, reference: "James 1:5", excerpt: "If any of you lacks wisdom, you should ask God, who gives generously." },
  { dayOfYear: 39, reference: "Hebrews 12:1", excerpt: "Let us run with perseverance the race marked out for us." },
  { dayOfYear: 40, reference: "1 John 4:19", excerpt: "We love because he first loved us." },
  { dayOfYear: 41, reference: "Psalm 91:1", excerpt: "Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty." },
  { dayOfYear: 42, reference: "Romans 8:38", excerpt: "For I am convinced that neither death nor life… will be able to separate us from the love of God." },
  { dayOfYear: 43, reference: "Matthew 28:20", excerpt: "And surely I am with you always, to the very end of the age." },
  { dayOfYear: 44, reference: "Psalm 16:11", excerpt: "You make known to me the path of life; you will fill me with joy in your presence." },
  { dayOfYear: 45, reference: "Proverbs 18:10", excerpt: "The name of the Lord is a fortified tower; the righteous run to it and are safe." },
  { dayOfYear: 46, reference: "Isaiah 43:2", excerpt: "When you pass through the waters, I will be with you." },
  { dayOfYear: 47, reference: "2 Corinthians 12:9", excerpt: "My grace is sufficient for you, for my power is made perfect in weakness." },
  { dayOfYear: 48, reference: "Galatians 2:20", excerpt: "I have been crucified with Christ and I no longer live, but Christ lives in me." },
  { dayOfYear: 49, reference: "Ephesians 6:10", excerpt: "Be strong in the Lord and in his mighty power." },
  { dayOfYear: 50, reference: "Colossians 3:23", excerpt: "Whatever you do, work at it with all your heart, as working for the Lord." },
  { dayOfYear: 51, reference: "1 Thessalonians 5:16", excerpt: "Rejoice always, pray continually, give thanks in all circumstances." },
  { dayOfYear: 52, reference: "Hebrews 13:5", excerpt: "Never will I leave you; never will I forsake you." },
  { dayOfYear: 53, reference: "James 1:2", excerpt: "Consider it pure joy whenever you face trials of many kinds." },
  { dayOfYear: 54, reference: "1 Peter 3:15", excerpt: "Always be prepared to give an answer to everyone who asks you the reason for the hope you have." },
  { dayOfYear: 55, reference: "1 John 1:9", excerpt: "If we confess our sins, he is faithful and just to forgive us our sins." },
  { dayOfYear: 56, reference: "Revelation 3:20", excerpt: "Here I am! I stand at the door and knock." },
  { dayOfYear: 57, reference: "Genesis 1:1", excerpt: "In the beginning God created the heavens and the earth." },
  { dayOfYear: 58, reference: "Exodus 14:14", excerpt: "The Lord will fight for you; you need only to be still." },
  { dayOfYear: 59, reference: "Deuteronomy 31:6", excerpt: "Be strong and courageous. Do not be afraid… for the Lord your God goes with you." },
  { dayOfYear: 60, reference: "Psalm 1:1", excerpt: "Blessed is the one who does not walk in step with the wicked." },
  { dayOfYear: 61, reference: "Psalm 19:1", excerpt: "The heavens declare the glory of God; the skies proclaim the work of his hands." },
  { dayOfYear: 62, reference: "Psalm 51:10", excerpt: "Create in me a pure heart, O God, and renew a steadfast spirit within me." },
  { dayOfYear: 63, reference: "Psalm 90:12", excerpt: "Teach us to number our days, that we may gain a heart of wisdom." },
  { dayOfYear: 64, reference: "Psalm 100:4", excerpt: "Enter his gates with thanksgiving and his courts with praise." },
  { dayOfYear: 65, reference: "Psalm 121:1", excerpt: "I lift up my eyes to the mountains—where does my help come from?" },
  { dayOfYear: 66, reference: "Psalm 121:2", excerpt: "My help comes from the Lord, the Maker of heaven and earth." },
  { dayOfYear: 67, reference: "Psalm 145:18", excerpt: "The Lord is near to all who call on him, to all who call on him in truth." },
  { dayOfYear: 68, reference: "Proverbs 3:6", excerpt: "In all your ways submit to him, and he will make your paths straight." },
  { dayOfYear: 69, reference: "Proverbs 4:23", excerpt: "Above all else, guard your heart, for everything you do flows from it." },
  { dayOfYear: 70, reference: "Proverbs 17:17", excerpt: "A friend loves at all times, and a brother is born for a time of adversity." },
  { dayOfYear: 71, reference: "Proverbs 27:17", excerpt: "As iron sharpens iron, so one person sharpens another." },
  { dayOfYear: 72, reference: "Ecclesiastes 3:1", excerpt: "There is a time for everything, and a season for every activity under the heavens." },
  { dayOfYear: 73, reference: "Isaiah 9:6", excerpt: "For to us a child is born, to us a son is given." },
  { dayOfYear: 74, reference: "Isaiah 53:5", excerpt: "But he was pierced for our transgressions, he was crushed for our iniquities." },
  { dayOfYear: 75, reference: "Isaiah 55:8", excerpt: "For my thoughts are not your thoughts, neither are your ways my ways." },
  { dayOfYear: 76, reference: "Jeremiah 17:7", excerpt: "Blessed is the one who trusts in the Lord, whose confidence is in him." },
  { dayOfYear: 77, reference: "Jeremiah 33:3", excerpt: "Call to me and I will answer you and tell you great and unsearchable things." },
  { dayOfYear: 78, reference: "Ezekiel 36:26", excerpt: "I will give you a new heart and put a new spirit in you." },
  { dayOfYear: 79, reference: "Micah 6:8", excerpt: "Act justly and love mercy and walk humbly with your God." },
  { dayOfYear: 80, reference: "Habakkuk 3:19", excerpt: "The Sovereign Lord is my strength; he makes my feet like the feet of a deer." },
  { dayOfYear: 81, reference: "Matthew 5:3", excerpt: "Blessed are the poor in spirit, for theirs is the kingdom of heaven." },
  { dayOfYear: 82, reference: "Matthew 5:9", excerpt: "Blessed are the peacemakers, for they will be called children of God." },
  { dayOfYear: 83, reference: "Matthew 6:21", excerpt: "For where your treasure is, there your heart will be also." },
  { dayOfYear: 84, reference: "Matthew 6:34", excerpt: "Therefore do not worry about tomorrow, for tomorrow will worry about itself." },
  { dayOfYear: 85, reference: "Matthew 7:7", excerpt: "Ask and it will be given to you; seek and you will find." },
  { dayOfYear: 86, reference: "Matthew 19:26", excerpt: "With man this is impossible, but with God all things are possible." },
  { dayOfYear: 87, reference: "Matthew 22:37", excerpt: "Love the Lord your God with all your heart and with all your soul." },
  { dayOfYear: 88, reference: "Mark 10:27", excerpt: "All things are possible with God." },
  { dayOfYear: 89, reference: "Mark 11:24", excerpt: "Whatever you ask for in prayer, believe that you have received it, and it will be yours." },
  { dayOfYear: 90, reference: "Luke 1:37", excerpt: "For no word from God will ever fail." },
  { dayOfYear: 91, reference: "Luke 6:31", excerpt: "Do to others as you would have them do to you." },
  { dayOfYear: 92, reference: "Luke 12:7", excerpt: "Indeed, the very hairs of your head are all numbered." },
  { dayOfYear: 93, reference: "John 1:1", excerpt: "In the beginning was the Word, and the Word was with God, and the Word was God." },
  { dayOfYear: 94, reference: "John 10:10", excerpt: "I have come that they may have life, and have it to the full." },
  { dayOfYear: 95, reference: "John 13:34", excerpt: "A new command I give you: Love one another." },
  { dayOfYear: 96, reference: "John 14:6", excerpt: "I am the way and the truth and the life." },
  { dayOfYear: 97, reference: "John 15:5", excerpt: "I am the vine; you are the branches." },
  { dayOfYear: 98, reference: "John 16:33", excerpt: "In this world you will have trouble. But take heart! I have overcome the world." },
  { dayOfYear: 99, reference: "Acts 1:8", excerpt: "You will receive power when the Holy Spirit comes on you." },
  { dayOfYear: 100, reference: "Acts 16:31", excerpt: "Believe in the Lord Jesus, and you will be saved." },
  { dayOfYear: 101, reference: "Romans 1:16", excerpt: "For I am not ashamed of the gospel, because it is the power of God for salvation." },
  { dayOfYear: 102, reference: "Romans 3:23", excerpt: "For all have sinned and fall short of the glory of God." },
  { dayOfYear: 103, reference: "Romans 6:23", excerpt: "For the wages of sin is death, but the gift of God is eternal life." },
  { dayOfYear: 104, reference: "Romans 8:1", excerpt: "There is therefore now no condemnation for those who are in Christ Jesus." },
  { dayOfYear: 105, reference: "Romans 8:31", excerpt: "If God is for us, who can be against us?" },
  { dayOfYear: 106, reference: "Romans 8:37", excerpt: "In all these things we are more than conquerors through him who loved us." },
  { dayOfYear: 107, reference: "Romans 12:12", excerpt: "Be joyful in hope, patient in affliction, faithful in prayer." },
  { dayOfYear: 108, reference: "Romans 12:21", excerpt: "Do not be overcome by evil, but overcome evil with good." },
  { dayOfYear: 109, reference: "1 Corinthians 10:13", excerpt: "God is faithful; he will not let you be tempted beyond what you can bear." },
  { dayOfYear: 110, reference: "1 Corinthians 15:58", excerpt: "Always give yourselves fully to the work of the Lord." },
  { dayOfYear: 111, reference: "1 Corinthians 16:14", excerpt: "Do everything in love." },
  { dayOfYear: 112, reference: "2 Corinthians 4:17", excerpt: "Our light and momentary troubles are achieving for us an eternal glory." },
  { dayOfYear: 113, reference: "2 Corinthians 5:7", excerpt: "For we live by faith, not by sight." },
  { dayOfYear: 114, reference: "2 Corinthians 9:7", excerpt: "God loves a cheerful giver." },
  { dayOfYear: 115, reference: "Galatians 6:9", excerpt: "Let us not become weary in doing good, for at the proper time we will reap a harvest." },
  { dayOfYear: 116, reference: "Ephesians 2:10", excerpt: "For we are God's handiwork, created in Christ Jesus to do good works." },
  { dayOfYear: 117, reference: "Ephesians 3:20", excerpt: "Now to him who is able to do immeasurably more than all we ask or imagine." },
  { dayOfYear: 118, reference: "Ephesians 4:32", excerpt: "Be kind and compassionate to one another, forgiving each other." },
  { dayOfYear: 119, reference: "Philippians 1:6", excerpt: "He who began a good work in you will carry it on to completion." },
  { dayOfYear: 120, reference: "Philippians 2:3", excerpt: "Do nothing out of selfish ambition, but in humility value others above yourselves." },
  { dayOfYear: 121, reference: "Philippians 4:8", excerpt: "Whatever is true, whatever is noble, whatever is right… think about such things." },
  { dayOfYear: 122, reference: "Philippians 4:19", excerpt: "And my God will meet all your needs according to the riches of his glory." },
  { dayOfYear: 123, reference: "Colossians 3:2", excerpt: "Set your minds on things above, not on earthly things." },
  { dayOfYear: 124, reference: "Colossians 3:12", excerpt: "Clothe yourselves with compassion, kindness, humility, gentleness and patience." },
  { dayOfYear: 125, reference: "1 Thessalonians 5:11", excerpt: "Therefore encourage one another and build each other up." },
  { dayOfYear: 126, reference: "2 Thessalonians 3:3", excerpt: "But the Lord is faithful, and he will strengthen you and protect you." },
  { dayOfYear: 127, reference: "1 Timothy 4:12", excerpt: "Don't let anyone look down on you because you are young." },
  { dayOfYear: 128, reference: "2 Timothy 3:16", excerpt: "All Scripture is God-breathed and is useful for teaching." },
  { dayOfYear: 129, reference: "Hebrews 4:12", excerpt: "For the word of God is alive and active." },
  { dayOfYear: 130, reference: "Hebrews 4:16", excerpt: "Let us then approach God's throne of grace with confidence." },
  { dayOfYear: 131, reference: "Hebrews 10:23", excerpt: "Let us hold unswervingly to the hope we profess, for he who promised is faithful." },
  { dayOfYear: 132, reference: "Hebrews 11:6", excerpt: "Without faith it is impossible to please God." },
  { dayOfYear: 133, reference: "Hebrews 12:2", excerpt: "Fixing our eyes on Jesus, the pioneer and perfecter of faith." },
  { dayOfYear: 134, reference: "Hebrews 13:8", excerpt: "Jesus Christ is the same yesterday and today and forever." },
  { dayOfYear: 135, reference: "James 1:17", excerpt: "Every good and perfect gift is from above." },
  { dayOfYear: 136, reference: "James 4:7", excerpt: "Submit yourselves, then, to God. Resist the devil, and he will flee from you." },
  { dayOfYear: 137, reference: "James 4:8", excerpt: "Come near to God and he will come near to you." },
  { dayOfYear: 138, reference: "1 Peter 1:3", excerpt: "Praise be to the God and Father of our Lord Jesus Christ!" },
  { dayOfYear: 139, reference: "1 Peter 2:9", excerpt: "But you are a chosen people, a royal priesthood, a holy nation." },
  { dayOfYear: 140, reference: "1 Peter 4:8", excerpt: "Above all, love each other deeply, because love covers over a multitude of sins." },
  { dayOfYear: 141, reference: "2 Peter 3:9", excerpt: "The Lord is not slow in keeping his promise… he is patient with you." },
  { dayOfYear: 142, reference: "1 John 3:1", excerpt: "See what great love the Father has lavished on us, that we should be called children of God!" },
  { dayOfYear: 143, reference: "1 John 4:8", excerpt: "Whoever does not love does not know God, because God is love." },
  { dayOfYear: 144, reference: "1 John 4:18", excerpt: "There is no fear in love. But perfect love drives out fear." },
  { dayOfYear: 145, reference: "1 John 5:14", excerpt: "This is the confidence we have in approaching God: that if we ask anything according to his will, he hears us." },
  { dayOfYear: 146, reference: "Revelation 21:4", excerpt: "He will wipe every tear from their eyes. There will be no more death or mourning." },
  { dayOfYear: 147, reference: "Psalm 8:3", excerpt: "When I consider your heavens, the work of your fingers, the moon and the stars…" },
  { dayOfYear: 148, reference: "Psalm 30:5", excerpt: "Weeping may stay for the night, but rejoicing comes in the morning." },
  { dayOfYear: 149, reference: "Psalm 32:8", excerpt: "I will instruct you and teach you in the way you should go." },
  { dayOfYear: 150, reference: "Psalm 42:1", excerpt: "As the deer pants for streams of water, so my soul pants for you, my God." },
  { dayOfYear: 151, reference: "Psalm 55:22", excerpt: "Cast your cares on the Lord and he will sustain you." },
  { dayOfYear: 152, reference: "Psalm 73:26", excerpt: "My flesh and my heart may fail, but God is the strength of my heart." },
  { dayOfYear: 153, reference: "Psalm 84:11", excerpt: "For the Lord God is a sun and shield; the Lord bestows favor and honor." },
  { dayOfYear: 154, reference: "Psalm 103:12", excerpt: "As far as the east is from the west, so far has he removed our transgressions from us." },
  { dayOfYear: 155, reference: "Psalm 118:24", excerpt: "This is the day that the Lord has made; let us rejoice and be glad in it." },
  { dayOfYear: 156, reference: "Psalm 138:8", excerpt: "The Lord will fulfill his purpose for me; your love, O Lord, endures forever." },
  { dayOfYear: 157, reference: "Psalm 143:8", excerpt: "Let the morning bring me word of your unfailing love, for I have put my trust in you." },
  { dayOfYear: 158, reference: "Psalm 147:3", excerpt: "He heals the brokenhearted and binds up their wounds." },
  { dayOfYear: 159, reference: "Jeremiah 29:11", excerpt: "For I know the plans I have for you, plans to prosper you and not to harm you, plans to give you hope and a future." },
  { dayOfYear: 160, reference: "Philippians 4:13", excerpt: "I can do all things through Christ who strengthens me." },
  { dayOfYear: 161, reference: "Psalm 23:1", excerpt: "The Lord is my shepherd; I shall not want." },
  { dayOfYear: 162, reference: "Romans 8:28", excerpt: "All things work together for good to those who love God." },
  { dayOfYear: 163, reference: "Isaiah 41:10", excerpt: "Fear not, for I am with you; be not dismayed, for I am your God." },
  { dayOfYear: 164, reference: "Proverbs 3:5", excerpt: "Trust in the Lord with all your heart, and lean not on your own understanding." },
  { dayOfYear: 165, reference: "John 3:16", excerpt: "For God so loved the world that he gave his only Son." },
  { dayOfYear: 166, reference: "Psalm 46:1", excerpt: "God is our refuge and strength, an ever-present help in trouble." },
  { dayOfYear: 167, reference: "Matthew 11:28", excerpt: "Come to me, all you who are weary and burdened, and I will give you rest." },
  { dayOfYear: 168, reference: "Joshua 1:9", excerpt: "Be strong and courageous. Do not be afraid; the Lord your God is with you." },
  { dayOfYear: 169, reference: "2 Corinthians 5:17", excerpt: "If anyone is in Christ, he is a new creation; the old has gone, the new has come." },
  { dayOfYear: 170, reference: "Psalm 27:1", excerpt: "The Lord is my light and my salvation—whom shall I fear?" },
  { dayOfYear: 171, reference: "Isaiah 40:31", excerpt: "Those who hope in the Lord will renew their strength." },
  { dayOfYear: 172, reference: "Romans 12:2", excerpt: "Do not conform to the pattern of this world, but be transformed." },
  { dayOfYear: 173, reference: "Galatians 5:22", excerpt: "The fruit of the Spirit is love, joy, peace, patience, kindness." },
  { dayOfYear: 174, reference: "Ephesians 2:8", excerpt: "For it is by grace you have been saved, through faith." },
  { dayOfYear: 175, reference: "Hebrews 11:1", excerpt: "Faith is confidence in what we hope for and assurance about what we do not see." },
  { dayOfYear: 176, reference: "1 Corinthians 13:4", excerpt: "Love is patient, love is kind. It does not envy, it does not boast." },
  { dayOfYear: 177, reference: "Psalm 119:105", excerpt: "Your word is a lamp for my feet, a light on my path." },
  { dayOfYear: 178, reference: "Matthew 6:33", excerpt: "Seek first the kingdom of God and his righteousness." },
  { dayOfYear: 179, reference: "Proverbs 16:3", excerpt: "Commit to the Lord whatever you do, and he will establish your plans." },
  { dayOfYear: 180, reference: "Psalm 37:4", excerpt: "Delight yourself in the Lord, and he will give you the desires of your heart." },
  { dayOfYear: 181, reference: "Romans 15:13", excerpt: "May the God of hope fill you with all joy and peace as you trust in him." },
  { dayOfYear: 182, reference: "Lamentations 3:22", excerpt: "Because of the Lord's great love we are not consumed; his mercies never fail." },
  { dayOfYear: 183, reference: "Zephaniah 3:17", excerpt: "The Lord your God is with you, the Mighty Warrior who saves." },
  { dayOfYear: 184, reference: "Psalm 34:18", excerpt: "The Lord is close to the brokenhearted and saves those crushed in spirit." },
  { dayOfYear: 185, reference: "1 Peter 5:7", excerpt: "Cast all your anxiety on him because he cares for you." },
  { dayOfYear: 186, reference: "John 14:27", excerpt: "Peace I leave with you; my peace I give you." },
  { dayOfYear: 187, reference: "Philippians 4:6", excerpt: "Do not be anxious about anything, but in every situation present your requests to God." },
  { dayOfYear: 188, reference: "Philippians 4:7", excerpt: "And the peace of God, which transcends all understanding, will guard your hearts." },
  { dayOfYear: 189, reference: "Matthew 5:16", excerpt: "Let your light shine before others, that they may see your good deeds." },
  { dayOfYear: 190, reference: "2 Timothy 1:7", excerpt: "God has not given us a spirit of fear, but of power and of love and of a sound mind." },
  { dayOfYear: 191, reference: "Romans 5:8", excerpt: "But God demonstrates his own love for us in this: While we were still sinners, Christ died for us." },
  { dayOfYear: 192, reference: "John 8:12", excerpt: "I am the light of the world. Whoever follows me will never walk in darkness." },
  { dayOfYear: 193, reference: "Psalm 139:14", excerpt: "I praise you because I am fearfully and wonderfully made." },
  { dayOfYear: 194, reference: "Isaiah 26:3", excerpt: "You will keep in perfect peace those whose minds are steadfast." },
  { dayOfYear: 195, reference: "Romans 10:9", excerpt: "If you declare with your mouth, 'Jesus is Lord,' you will be saved." },
  { dayOfYear: 196, reference: "James 1:5", excerpt: "If any of you lacks wisdom, you should ask God, who gives generously." },
  { dayOfYear: 197, reference: "Hebrews 12:1", excerpt: "Let us run with perseverance the race marked out for us." },
  { dayOfYear: 198, reference: "1 John 4:19", excerpt: "We love because he first loved us." },
  { dayOfYear: 199, reference: "Psalm 91:1", excerpt: "Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty." },
  { dayOfYear: 200, reference: "Romans 8:38", excerpt: "For I am convinced that neither death nor life… will be able to separate us from the love of God." },
  { dayOfYear: 201, reference: "Matthew 28:20", excerpt: "And surely I am with you always, to the very end of the age." },
  { dayOfYear: 202, reference: "Psalm 16:11", excerpt: "You make known to me the path of life; you will fill me with joy in your presence." },
  { dayOfYear: 203, reference: "Proverbs 18:10", excerpt: "The name of the Lord is a fortified tower; the righteous run to it and are safe." },
  { dayOfYear: 204, reference: "Isaiah 43:2", excerpt: "When you pass through the waters, I will be with you." },
  { dayOfYear: 205, reference: "2 Corinthians 12:9", excerpt: "My grace is sufficient for you, for my power is made perfect in weakness." },
  { dayOfYear: 206, reference: "Galatians 2:20", excerpt: "I have been crucified with Christ and I no longer live, but Christ lives in me." },
  { dayOfYear: 207, reference: "Ephesians 6:10", excerpt: "Be strong in the Lord and in his mighty power." },
  { dayOfYear: 208, reference: "Colossians 3:23", excerpt: "Whatever you do, work at it with all your heart, as working for the Lord." },
  { dayOfYear: 209, reference: "1 Thessalonians 5:16", excerpt: "Rejoice always, pray continually, give thanks in all circumstances." },
  { dayOfYear: 210, reference: "Hebrews 13:5", excerpt: "Never will I leave you; never will I forsake you." },
  { dayOfYear: 211, reference: "James 1:2", excerpt: "Consider it pure joy whenever you face trials of many kinds." },
  { dayOfYear: 212, reference: "1 Peter 3:15", excerpt: "Always be prepared to give an answer to everyone who asks you the reason for the hope you have." },
  { dayOfYear: 213, reference: "1 John 1:9", excerpt: "If we confess our sins, he is faithful and just to forgive us our sins." },
  { dayOfYear: 214, reference: "Revelation 3:20", excerpt: "Here I am! I stand at the door and knock." },
  { dayOfYear: 215, reference: "Genesis 1:1", excerpt: "In the beginning God created the heavens and the earth." },
  { dayOfYear: 216, reference: "Exodus 14:14", excerpt: "The Lord will fight for you; you need only to be still." },
  { dayOfYear: 217, reference: "Deuteronomy 31:6", excerpt: "Be strong and courageous. Do not be afraid… for the Lord your God goes with you." },
  { dayOfYear: 218, reference: "Psalm 1:1", excerpt: "Blessed is the one who does not walk in step with the wicked." },
  { dayOfYear: 219, reference: "Psalm 19:1", excerpt: "The heavens declare the glory of God; the skies proclaim the work of his hands." },
  { dayOfYear: 220, reference: "Psalm 51:10", excerpt: "Create in me a pure heart, O God, and renew a steadfast spirit within me." },
  { dayOfYear: 221, reference: "Psalm 90:12", excerpt: "Teach us to number our days, that we may gain a heart of wisdom." },
  { dayOfYear: 222, reference: "Psalm 100:4", excerpt: "Enter his gates with thanksgiving and his courts with praise." },
  { dayOfYear: 223, reference: "Psalm 121:1", excerpt: "I lift up my eyes to the mountains—where does my help come from?" },
  { dayOfYear: 224, reference: "Psalm 121:2", excerpt: "My help comes from the Lord, the Maker of heaven and earth." },
  { dayOfYear: 225, reference: "Psalm 145:18", excerpt: "The Lord is near to all who call on him, to all who call on him in truth." },
  { dayOfYear: 226, reference: "Proverbs 3:6", excerpt: "In all your ways submit to him, and he will make your paths straight." },
  { dayOfYear: 227, reference: "Proverbs 4:23", excerpt: "Above all else, guard your heart, for everything you do flows from it." },
  { dayOfYear: 228, reference: "Proverbs 17:17", excerpt: "A friend loves at all times, and a brother is born for a time of adversity." },
  { dayOfYear: 229, reference: "Proverbs 27:17", excerpt: "As iron sharpens iron, so one person sharpens another." },
  { dayOfYear: 230, reference: "Ecclesiastes 3:1", excerpt: "There is a time for everything, and a season for every activity under the heavens." },
  { dayOfYear: 231, reference: "Isaiah 9:6", excerpt: "For to us a child is born, to us a son is given." },
  { dayOfYear: 232, reference: "Isaiah 53:5", excerpt: "But he was pierced for our transgressions, he was crushed for our iniquities." },
  { dayOfYear: 233, reference: "Isaiah 55:8", excerpt: "For my thoughts are not your thoughts, neither are your ways my ways." },
  { dayOfYear: 234, reference: "Jeremiah 17:7", excerpt: "Blessed is the one who trusts in the Lord, whose confidence is in him." },
  { dayOfYear: 235, reference: "Jeremiah 33:3", excerpt: "Call to me and I will answer you and tell you great and unsearchable things." },
  { dayOfYear: 236, reference: "Ezekiel 36:26", excerpt: "I will give you a new heart and put a new spirit in you." },
  { dayOfYear: 237, reference: "Micah 6:8", excerpt: "Act justly and love mercy and walk humbly with your God." },
  { dayOfYear: 238, reference: "Habakkuk 3:19", excerpt: "The Sovereign Lord is my strength; he makes my feet like the feet of a deer." },
  { dayOfYear: 239, reference: "Matthew 5:3", excerpt: "Blessed are the poor in spirit, for theirs is the kingdom of heaven." },
  { dayOfYear: 240, reference: "Matthew 5:9", excerpt: "Blessed are the peacemakers, for they will be called children of God." },
  { dayOfYear: 241, reference: "Matthew 6:21", excerpt: "For where your treasure is, there your heart will be also." },
  { dayOfYear: 242, reference: "Matthew 6:34", excerpt: "Therefore do not worry about tomorrow, for tomorrow will worry about itself." },
  { dayOfYear: 243, reference: "Matthew 7:7", excerpt: "Ask and it will be given to you; seek and you will find." },
  { dayOfYear: 244, reference: "Matthew 19:26", excerpt: "With man this is impossible, but with God all things are possible." },
  { dayOfYear: 245, reference: "Matthew 22:37", excerpt: "Love the Lord your God with all your heart and with all your soul." },
  { dayOfYear: 246, reference: "Mark 10:27", excerpt: "All things are possible with God." },
  { dayOfYear: 247, reference: "Mark 11:24", excerpt: "Whatever you ask for in prayer, believe that you have received it, and it will be yours." },
  { dayOfYear: 248, reference: "Luke 1:37", excerpt: "For no word from God will ever fail." },
  { dayOfYear: 249, reference: "Luke 6:31", excerpt: "Do to others as you would have them do to you." },
  { dayOfYear: 250, reference: "Luke 12:7", excerpt: "Indeed, the very hairs of your head are all numbered." },
  { dayOfYear: 251, reference: "John 1:1", excerpt: "In the beginning was the Word, and the Word was with God, and the Word was God." },
  { dayOfYear: 252, reference: "John 10:10", excerpt: "I have come that they may have life, and have it to the full." },
  { dayOfYear: 253, reference: "John 13:34", excerpt: "A new command I give you: Love one another." },
  { dayOfYear: 254, reference: "John 14:6", excerpt: "I am the way and the truth and the life." },
  { dayOfYear: 255, reference: "John 15:5", excerpt: "I am the vine; you are the branches." },
  { dayOfYear: 256, reference: "John 16:33", excerpt: "In this world you will have trouble. But take heart! I have overcome the world." },
  { dayOfYear: 257, reference: "Acts 1:8", excerpt: "You will receive power when the Holy Spirit comes on you." },
  { dayOfYear: 258, reference: "Acts 16:31", excerpt: "Believe in the Lord Jesus, and you will be saved." },
  { dayOfYear: 259, reference: "Romans 1:16", excerpt: "For I am not ashamed of the gospel, because it is the power of God for salvation." },
  { dayOfYear: 260, reference: "Romans 3:23", excerpt: "For all have sinned and fall short of the glory of God." },
  { dayOfYear: 261, reference: "Romans 6:23", excerpt: "For the wages of sin is death, but the gift of God is eternal life." },
  { dayOfYear: 262, reference: "Romans 8:1", excerpt: "There is therefore now no condemnation for those who are in Christ Jesus." },
  { dayOfYear: 263, reference: "Romans 8:31", excerpt: "If God is for us, who can be against us?" },
  { dayOfYear: 264, reference: "Romans 8:37", excerpt: "In all these things we are more than conquerors through him who loved us." },
  { dayOfYear: 265, reference: "Romans 12:12", excerpt: "Be joyful in hope, patient in affliction, faithful in prayer." },
  { dayOfYear: 266, reference: "Romans 12:21", excerpt: "Do not be overcome by evil, but overcome evil with good." },
  { dayOfYear: 267, reference: "1 Corinthians 10:13", excerpt: "God is faithful; he will not let you be tempted beyond what you can bear." },
  { dayOfYear: 268, reference: "1 Corinthians 15:58", excerpt: "Always give yourselves fully to the work of the Lord." },
  { dayOfYear: 269, reference: "1 Corinthians 16:14", excerpt: "Do everything in love." },
  { dayOfYear: 270, reference: "2 Corinthians 4:17", excerpt: "Our light and momentary troubles are achieving for us an eternal glory." },
  { dayOfYear: 271, reference: "2 Corinthians 5:7", excerpt: "For we live by faith, not by sight." },
  { dayOfYear: 272, reference: "2 Corinthians 9:7", excerpt: "God loves a cheerful giver." },
  { dayOfYear: 273, reference: "Galatians 6:9", excerpt: "Let us not become weary in doing good, for at the proper time we will reap a harvest." },
  { dayOfYear: 274, reference: "Ephesians 2:10", excerpt: "For we are God's handiwork, created in Christ Jesus to do good works." },
  { dayOfYear: 275, reference: "Ephesians 3:20", excerpt: "Now to him who is able to do immeasurably more than all we ask or imagine." },
  { dayOfYear: 276, reference: "Ephesians 4:32", excerpt: "Be kind and compassionate to one another, forgiving each other." },
  { dayOfYear: 277, reference: "Philippians 1:6", excerpt: "He who began a good work in you will carry it on to completion." },
  { dayOfYear: 278, reference: "Philippians 2:3", excerpt: "Do nothing out of selfish ambition, but in humility value others above yourselves." },
  { dayOfYear: 279, reference: "Philippians 4:8", excerpt: "Whatever is true, whatever is noble, whatever is right… think about such things." },
  { dayOfYear: 280, reference: "Philippians 4:19", excerpt: "And my God will meet all your needs according to the riches of his glory." },
  { dayOfYear: 281, reference: "Colossians 3:2", excerpt: "Set your minds on things above, not on earthly things." },
  { dayOfYear: 282, reference: "Colossians 3:12", excerpt: "Clothe yourselves with compassion, kindness, humility, gentleness and patience." },
  { dayOfYear: 283, reference: "1 Thessalonians 5:11", excerpt: "Therefore encourage one another and build each other up." },
  { dayOfYear: 284, reference: "2 Thessalonians 3:3", excerpt: "But the Lord is faithful, and he will strengthen you and protect you." },
  { dayOfYear: 285, reference: "1 Timothy 4:12", excerpt: "Don't let anyone look down on you because you are young." },
  { dayOfYear: 286, reference: "2 Timothy 3:16", excerpt: "All Scripture is God-breathed and is useful for teaching." },
  { dayOfYear: 287, reference: "Hebrews 4:12", excerpt: "For the word of God is alive and active." },
  { dayOfYear: 288, reference: "Hebrews 4:16", excerpt: "Let us then approach God's throne of grace with confidence." },
  { dayOfYear: 289, reference: "Hebrews 10:23", excerpt: "Let us hold unswervingly to the hope we profess, for he who promised is faithful." },
  { dayOfYear: 290, reference: "Hebrews 11:6", excerpt: "Without faith it is impossible to please God." },
  { dayOfYear: 291, reference: "Hebrews 12:2", excerpt: "Fixing our eyes on Jesus, the pioneer and perfecter of faith." },
  { dayOfYear: 292, reference: "Hebrews 13:8", excerpt: "Jesus Christ is the same yesterday and today and forever." },
  { dayOfYear: 293, reference: "James 1:17", excerpt: "Every good and perfect gift is from above." },
  { dayOfYear: 294, reference: "James 4:7", excerpt: "Submit yourselves, then, to God. Resist the devil, and he will flee from you." },
  { dayOfYear: 295, reference: "James 4:8", excerpt: "Come near to God and he will come near to you." },
  { dayOfYear: 296, reference: "1 Peter 1:3", excerpt: "Praise be to the God and Father of our Lord Jesus Christ!" },
  { dayOfYear: 297, reference: "1 Peter 2:9", excerpt: "But you are a chosen people, a royal priesthood, a holy nation." },
  { dayOfYear: 298, reference: "1 Peter 4:8", excerpt: "Above all, love each other deeply, because love covers over a multitude of sins." },
  { dayOfYear: 299, reference: "2 Peter 3:9", excerpt: "The Lord is not slow in keeping his promise… he is patient with you." },
  { dayOfYear: 300, reference: "1 John 3:1", excerpt: "See what great love the Father has lavished on us, that we should be called children of God!" },
  { dayOfYear: 301, reference: "1 John 4:8", excerpt: "Whoever does not love does not know God, because God is love." },
  { dayOfYear: 302, reference: "1 John 4:18", excerpt: "There is no fear in love. But perfect love drives out fear." },
  { dayOfYear: 303, reference: "1 John 5:14", excerpt: "This is the confidence we have in approaching God: that if we ask anything according to his will, he hears us." },
  { dayOfYear: 304, reference: "Revelation 21:4", excerpt: "He will wipe every tear from their eyes. There will be no more death or mourning." },
  { dayOfYear: 305, reference: "Psalm 8:3", excerpt: "When I consider your heavens, the work of your fingers, the moon and the stars…" },
  { dayOfYear: 306, reference: "Psalm 30:5", excerpt: "Weeping may stay for the night, but rejoicing comes in the morning." },
  { dayOfYear: 307, reference: "Psalm 32:8", excerpt: "I will instruct you and teach you in the way you should go." },
  { dayOfYear: 308, reference: "Psalm 42:1", excerpt: "As the deer pants for streams of water, so my soul pants for you, my God." },
  { dayOfYear: 309, reference: "Psalm 55:22", excerpt: "Cast your cares on the Lord and he will sustain you." },
  { dayOfYear: 310, reference: "Psalm 73:26", excerpt: "My flesh and my heart may fail, but God is the strength of my heart." },
  { dayOfYear: 311, reference: "Psalm 84:11", excerpt: "For the Lord God is a sun and shield; the Lord bestows favor and honor." },
  { dayOfYear: 312, reference: "Psalm 103:12", excerpt: "As far as the east is from the west, so far has he removed our transgressions from us." },
  { dayOfYear: 313, reference: "Psalm 118:24", excerpt: "This is the day that the Lord has made; let us rejoice and be glad in it." },
  { dayOfYear: 314, reference: "Psalm 138:8", excerpt: "The Lord will fulfill his purpose for me; your love, O Lord, endures forever." },
  { dayOfYear: 315, reference: "Psalm 143:8", excerpt: "Let the morning bring me word of your unfailing love, for I have put my trust in you." },
  { dayOfYear: 316, reference: "Psalm 147:3", excerpt: "He heals the brokenhearted and binds up their wounds." },
  { dayOfYear: 317, reference: "Jeremiah 29:11", excerpt: "For I know the plans I have for you, plans to prosper you and not to harm you, plans to give you hope and a future." },
  { dayOfYear: 318, reference: "Philippians 4:13", excerpt: "I can do all things through Christ who strengthens me." },
  { dayOfYear: 319, reference: "Psalm 23:1", excerpt: "The Lord is my shepherd; I shall not want." },
  { dayOfYear: 320, reference: "Romans 8:28", excerpt: "All things work together for good to those who love God." },
  { dayOfYear: 321, reference: "Isaiah 41:10", excerpt: "Fear not, for I am with you; be not dismayed, for I am your God." },
  { dayOfYear: 322, reference: "Proverbs 3:5", excerpt: "Trust in the Lord with all your heart, and lean not on your own understanding." },
  { dayOfYear: 323, reference: "John 3:16", excerpt: "For God so loved the world that he gave his only Son." },
  { dayOfYear: 324, reference: "Psalm 46:1", excerpt: "God is our refuge and strength, an ever-present help in trouble." },
  { dayOfYear: 325, reference: "Matthew 11:28", excerpt: "Come to me, all you who are weary and burdened, and I will give you rest." },
  { dayOfYear: 326, reference: "Joshua 1:9", excerpt: "Be strong and courageous. Do not be afraid; the Lord your God is with you." },
  { dayOfYear: 327, reference: "2 Corinthians 5:17", excerpt: "If anyone is in Christ, he is a new creation; the old has gone, the new has come." },
  { dayOfYear: 328, reference: "Psalm 27:1", excerpt: "The Lord is my light and my salvation—whom shall I fear?" },
  { dayOfYear: 329, reference: "Isaiah 40:31", excerpt: "Those who hope in the Lord will renew their strength." },
  { dayOfYear: 330, reference: "Romans 12:2", excerpt: "Do not conform to the pattern of this world, but be transformed." },
  { dayOfYear: 331, reference: "Galatians 5:22", excerpt: "The fruit of the Spirit is love, joy, peace, patience, kindness." },
  { dayOfYear: 332, reference: "Ephesians 2:8", excerpt: "For it is by grace you have been saved, through faith." },
  { dayOfYear: 333, reference: "Hebrews 11:1", excerpt: "Faith is confidence in what we hope for and assurance about what we do not see." },
  { dayOfYear: 334, reference: "1 Corinthians 13:4", excerpt: "Love is patient, love is kind. It does not envy, it does not boast." },
  { dayOfYear: 335, reference: "Psalm 119:105", excerpt: "Your word is a lamp for my feet, a light on my path." },
  { dayOfYear: 336, reference: "Matthew 6:33", excerpt: "Seek first the kingdom of God and his righteousness." },
  { dayOfYear: 337, reference: "Proverbs 16:3", excerpt: "Commit to the Lord whatever you do, and he will establish your plans." },
  { dayOfYear: 338, reference: "Psalm 37:4", excerpt: "Delight yourself in the Lord, and he will give you the desires of your heart." },
  { dayOfYear: 339, reference: "Romans 15:13", excerpt: "May the God of hope fill you with all joy and peace as you trust in him." },
  { dayOfYear: 340, reference: "Lamentations 3:22", excerpt: "Because of the Lord's great love we are not consumed; his mercies never fail." },
  { dayOfYear: 341, reference: "Zephaniah 3:17", excerpt: "The Lord your God is with you, the Mighty Warrior who saves." },
  { dayOfYear: 342, reference: "Psalm 34:18", excerpt: "The Lord is close to the brokenhearted and saves those crushed in spirit." },
  { dayOfYear: 343, reference: "1 Peter 5:7", excerpt: "Cast all your anxiety on him because he cares for you." },
  { dayOfYear: 344, reference: "John 14:27", excerpt: "Peace I leave with you; my peace I give you." },
  { dayOfYear: 345, reference: "Philippians 4:6", excerpt: "Do not be anxious about anything, but in every situation present your requests to God." },
  { dayOfYear: 346, reference: "Philippians 4:7", excerpt: "And the peace of God, which transcends all understanding, will guard your hearts." },
  { dayOfYear: 347, reference: "Matthew 5:16", excerpt: "Let your light shine before others, that they may see your good deeds." },
  { dayOfYear: 348, reference: "2 Timothy 1:7", excerpt: "God has not given us a spirit of fear, but of power and of love and of a sound mind." },
  { dayOfYear: 349, reference: "Romans 5:8", excerpt: "But God demonstrates his own love for us in this: While we were still sinners, Christ died for us." },
  { dayOfYear: 350, reference: "John 8:12", excerpt: "I am the light of the world. Whoever follows me will never walk in darkness." },
  { dayOfYear: 351, reference: "Psalm 139:14", excerpt: "I praise you because I am fearfully and wonderfully made." },
  { dayOfYear: 352, reference: "Isaiah 26:3", excerpt: "You will keep in perfect peace those whose minds are steadfast." },
  { dayOfYear: 353, reference: "Romans 10:9", excerpt: "If you declare with your mouth, 'Jesus is Lord,' you will be saved." },
  { dayOfYear: 354, reference: "James 1:5", excerpt: "If any of you lacks wisdom, you should ask God, who gives generously." },
  { dayOfYear: 355, reference: "Hebrews 12:1", excerpt: "Let us run with perseverance the race marked out for us." },
  { dayOfYear: 356, reference: "1 John 4:19", excerpt: "We love because he first loved us." },
  { dayOfYear: 357, reference: "Psalm 91:1", excerpt: "Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty." },
  { dayOfYear: 358, reference: "Romans 8:38", excerpt: "For I am convinced that neither death nor life… will be able to separate us from the love of God." },
  { dayOfYear: 359, reference: "Matthew 28:20", excerpt: "And surely I am with you always, to the very end of the age." },
  { dayOfYear: 360, reference: "Psalm 16:11", excerpt: "You make known to me the path of life; you will fill me with joy in your presence." },
  { dayOfYear: 361, reference: "Proverbs 18:10", excerpt: "The name of the Lord is a fortified tower; the righteous run to it and are safe." },
  { dayOfYear: 362, reference: "Isaiah 43:2", excerpt: "When you pass through the waters, I will be with you." },
  { dayOfYear: 363, reference: "2 Corinthians 12:9", excerpt: "My grace is sufficient for you, for my power is made perfect in weakness." },
  { dayOfYear: 364, reference: "Galatians 2:20", excerpt: "I have been crucified with Christ and I no longer live, but Christ lives in me." },
  { dayOfYear: 365, reference: "Ephesians 6:10", excerpt: "Be strong in the Lord and in his mighty power." },
];

export function getDayOfYearForDate(d: Date): number {
  const start = Date.UTC(d.getUTCFullYear(), 0, 0);
  const now = Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate());
  const doy = Math.floor((now - start) / 86400000); // 1..366
  // Leap year handling: on Feb 29 (doy 60 in a leap year) use day 180.
  // On Mar 1+ in a leap year, shift back by 1 so the normal 1..365 mapping continues.
  const y = d.getUTCFullYear();
  const isLeap = (y % 4 === 0 && y % 100 !== 0) || y % 400 === 0;
  if (!isLeap) return Math.min(doy, 365);
  if (doy === 60) return 180; // Feb 29
  if (doy >= 61) return doy - 1;
  return doy;
}