import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms & Conditions — VerseSmart" },
      { name: "description", content: "The terms governing your use of VerseSmart, including subscriptions, acceptable use, and liability." },
      { property: "og:title", content: "Terms & Conditions — VerseSmart" },
      { property: "og:description", content: "The terms governing your use of VerseSmart, including subscriptions, acceptable use, and liability." },
      { property: "og:url", content: "https://versesmart.org/terms" },
    ],
    links: [{ rel: "canonical", href: "https://versesmart.org/terms" }],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <main className="prose prose-sm sm:prose-base mx-auto max-w-3xl px-5 py-12 sm:py-16">
      <h1>Terms & Conditions</h1>
      <p>
        <em>
          Last updated: {new Date().toLocaleDateString("en-GB", { year: "numeric", month: "long", day: "numeric" })}
        </em>
      </p>

      <p>
        These terms govern your use of Verse Smart ("the Service"), operated by <strong>REF</strong> ("we", "us"). By
        using the Service you agree to these terms.
      </p>

      <h2>1. The Service</h2>
      <p>
        Verse Smart provides AI-rendered summaries of public-domain Bible commentaries (Matthew Henry, John Calvin,
        Charles Spurgeon, Albert Barnes, John Wesley) for any Bible passage you choose. Summaries are study aids; they
        are not original quotations.
      </p>

      <h2>2. Acceptance & authority</h2>
      <p>
        By continuing to use the Service you agree to these terms. You confirm you are of legal age in your jurisdiction
        (or have parental consent). If you use the Service on behalf of an organisation you confirm you have authority
        to bind it.
      </p>

      <h2>3. Account & accuracy</h2>
      <p>
        You are responsible for keeping your account credentials confidential and for activity under your account. You
        agree to provide accurate information and keep it up to date.
      </p>

      <h2>4. Acceptable use</h2>
      <p>
        You must not misuse the Service. In particular you must not: (a) use it unlawfully; (b) attempt fraud or spam;
        (c) infringe intellectual property rights; (d) interfere with security, including probing, scanning, scraping,
        distributing malware, or attempting to bypass technical limits; (e) reverse engineer or resell the Service; or
        (f) use the Service to generate content that is illegal, hateful, or defamatory.
      </p>

      <h2>5. AI-generated content</h2>
      <p>
        Summaries are generated by AI and may contain errors, omissions, or misattributions. They are for general study
        and educational purposes only and are not a substitute for primary sources, original commentary, theological
        advice, or pastoral counsel. You are responsible for verifying anything you rely on.
      </p>

      <h2>6. Intellectual property</h2>
      <p>
        The Service, including its software, design, branding, and AI-generated summaries, is owned by us. We grant you
        a limited, non-exclusive, non-transferable right to use the Service for your personal study within the plan you
        have selected. The underlying public-domain commentaries remain in the public domain.
      </p>

      <h2>7. Payment, subscriptions, and refunds</h2>
      <p>
        Our order process is conducted by our online reseller <strong>Paddle.com</strong>.{" "}
        <strong>Paddle.com is the Merchant of Record for all our orders.</strong> Paddle provides all customer service
        inquiries and handles returns. Payment, billing, tax, cancellation, and refund mechanics are governed by
        Paddle's{" "}
        <a href="https://www.paddle.com/legal/checkout-buyer-terms" target="_blank" rel="noopener noreferrer">
          Buyer Terms
        </a>
        . Subscriptions auto-renew at the end of each billing period unless cancelled. See our{" "}
        <a href="/refund">Refund Policy</a>.
      </p>

      <h2>8. Service level</h2>
      <p>
        We work to keep the Service available but do not guarantee uninterrupted or error-free operation. To the fullest
        extent permitted by law, we disclaim all implied warranties including merchantability and fitness for a
        particular purpose.
      </p>

      <h2>9. Liability</h2>
      <p>
        To the fullest extent permitted by law, our aggregate liability arising out of or related to the Service is
        capped at the fees you paid us in the 12 months prior to the event giving rise to the claim. We exclude
        liability for indirect, consequential, special, or incidental damages, including loss of profits, data, or
        goodwill. Nothing in these terms limits liability for fraud, death, or personal injury where such limitation is
        prohibited by law.
      </p>

      <h2>10. Indemnity</h2>
      <p>
        You agree to indemnify us against claims arising from your unlawful use of the Service or your breach of these
        terms.
      </p>

      <h2>11. Suspension & termination</h2>
      <p>
        We may suspend or terminate your access for material breach of these terms, non-payment, fraud or security risk,
        or repeated or serious policy violations. On termination your right to use the Service ends; we may delete your
        data after a reasonable period.
      </p>

      <h2>12. Changes</h2>
      <p>
        We may update these terms from time to time. Continued use after changes take effect constitutes acceptance.
      </p>

      <h2>13. Governing law</h2>
      <p>
        These terms are governed by the laws of the seller's place of residence. Disputes will be resolved in the
        competent courts of that jurisdiction, subject to any mandatory consumer rights you may have where you live.
      </p>

      <h2>14. Contact</h2>
      <p>
        Questions about these terms? Contact us through the email shown in the Paddle receipt for your order, or via our
        support page.
      </p>
    </main>
  );
}
