/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CopyrightRouteImport } from './routes/copyright'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as VerseSlugRouteImport } from './routes/verse.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogLangLangIndexRouteImport } from './routes/blog.lang.$lang.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as BlogLangLangSlugRouteImport } from './routes/blog.lang.$lang.$slug'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksWarmVerseCacheRouteImport } from './routes/api/public/hooks/warm-verse-cache'
import { Route as ApiPublicHooksDailyVotdWebhookRouteImport } from './routes/api/public/hooks/daily-votd-webhook'
import { Route as ApiPublicHooksCommentatorAuditRouteImport } from './routes/api/public/hooks/commentator-audit'
import { Route as ApiPublicAdminNewUserNotifyRouteImport } from './routes/api/public/admin/new-user-notify'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightRoute = CopyrightRouteImport.update({
  id: '/copyright',
  path: '/copyright',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerseSlugRoute = VerseSlugRouteImport.update({
  id: '/verse/$slug',
  path: '/verse/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogLangLangIndexRoute = BlogLangLangIndexRouteImport.update({
  id: '/blog/lang/$lang/',
  path: '/blog/lang/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogLangLangSlugRoute = BlogLangLangSlugRouteImport.update({
  id: '/blog/lang/$lang/$slug',
  path: '/blog/lang/$lang/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWarmVerseCacheRoute =
  ApiPublicHooksWarmVerseCacheRouteImport.update({
    id: '/api/public/hooks/warm-verse-cache',
    path: '/api/public/hooks/warm-verse-cache',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyVotdWebhookRoute =
  ApiPublicHooksDailyVotdWebhookRouteImport.update({
    id: '/api/public/hooks/daily-votd-webhook',
    path: '/api/public/hooks/daily-votd-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCommentatorAuditRoute =
  ApiPublicHooksCommentatorAuditRouteImport.update({
    id: '/api/public/hooks/commentator-audit',
    path: '/api/public/hooks/commentator-audit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminNewUserNotifyRoute =
  ApiPublicAdminNewUserNotifyRouteImport.update({
    id: '/api/public/admin/new-user-notify',
    path: '/api/public/admin/new-user-notify',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/copyright': typeof CopyrightRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/verse/$slug': typeof VerseSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/admin/new-user-notify': typeof ApiPublicAdminNewUserNotifyRoute
  '/api/public/hooks/commentator-audit': typeof ApiPublicHooksCommentatorAuditRoute
  '/api/public/hooks/daily-votd-webhook': typeof ApiPublicHooksDailyVotdWebhookRoute
  '/api/public/hooks/warm-verse-cache': typeof ApiPublicHooksWarmVerseCacheRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/blog/lang/$lang/$slug': typeof BlogLangLangSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/blog/lang/$lang/': typeof BlogLangLangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/copyright': typeof CopyrightRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/verse/$slug': typeof VerseSlugRoute
  '/blog': typeof BlogIndexRoute
  '/api/public/admin/new-user-notify': typeof ApiPublicAdminNewUserNotifyRoute
  '/api/public/hooks/commentator-audit': typeof ApiPublicHooksCommentatorAuditRoute
  '/api/public/hooks/daily-votd-webhook': typeof ApiPublicHooksDailyVotdWebhookRoute
  '/api/public/hooks/warm-verse-cache': typeof ApiPublicHooksWarmVerseCacheRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/blog/lang/$lang/$slug': typeof BlogLangLangSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/blog/lang/$lang': typeof BlogLangLangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/copyright': typeof CopyrightRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/verse/$slug': typeof VerseSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/admin/new-user-notify': typeof ApiPublicAdminNewUserNotifyRoute
  '/api/public/hooks/commentator-audit': typeof ApiPublicHooksCommentatorAuditRoute
  '/api/public/hooks/daily-votd-webhook': typeof ApiPublicHooksDailyVotdWebhookRoute
  '/api/public/hooks/warm-verse-cache': typeof ApiPublicHooksWarmVerseCacheRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/blog/lang/$lang/$slug': typeof BlogLangLangSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/blog/lang/$lang/': typeof BlogLangLangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/contact'
    | '/copyright'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/verse/$slug'
    | '/blog/'
    | '/api/public/admin/new-user-notify'
    | '/api/public/hooks/commentator-audit'
    | '/api/public/hooks/daily-votd-webhook'
    | '/api/public/hooks/warm-verse-cache'
    | '/api/public/payments/webhook'
    | '/blog/lang/$lang/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/blog/lang/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/contact'
    | '/copyright'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/verse/$slug'
    | '/blog'
    | '/api/public/admin/new-user-notify'
    | '/api/public/hooks/commentator-audit'
    | '/api/public/hooks/daily-votd-webhook'
    | '/api/public/hooks/warm-verse-cache'
    | '/api/public/payments/webhook'
    | '/blog/lang/$lang/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/blog/lang/$lang'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/contact'
    | '/copyright'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/verse/$slug'
    | '/blog/'
    | '/api/public/admin/new-user-notify'
    | '/api/public/hooks/commentator-audit'
    | '/api/public/hooks/daily-votd-webhook'
    | '/api/public/hooks/warm-verse-cache'
    | '/api/public/payments/webhook'
    | '/blog/lang/$lang/$slug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/blog/lang/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  CopyrightRoute: typeof CopyrightRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  VerseSlugRoute: typeof VerseSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicAdminNewUserNotifyRoute: typeof ApiPublicAdminNewUserNotifyRoute
  ApiPublicHooksCommentatorAuditRoute: typeof ApiPublicHooksCommentatorAuditRoute
  ApiPublicHooksDailyVotdWebhookRoute: typeof ApiPublicHooksDailyVotdWebhookRoute
  ApiPublicHooksWarmVerseCacheRoute: typeof ApiPublicHooksWarmVerseCacheRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  BlogLangLangSlugRoute: typeof BlogLangLangSlugRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  BlogLangLangIndexRoute: typeof BlogLangLangIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright': {
      id: '/copyright'
      path: '/copyright'
      fullPath: '/copyright'
      preLoaderRoute: typeof CopyrightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verse/$slug': {
      id: '/verse/$slug'
      path: '/verse/$slug'
      fullPath: '/verse/$slug'
      preLoaderRoute: typeof VerseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/lang/$lang/': {
      id: '/blog/lang/$lang/'
      path: '/blog/lang/$lang'
      fullPath: '/blog/lang/$lang/'
      preLoaderRoute: typeof BlogLangLangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/lang/$lang/$slug': {
      id: '/blog/lang/$lang/$slug'
      path: '/blog/lang/$lang/$slug'
      fullPath: '/blog/lang/$lang/$slug'
      preLoaderRoute: typeof BlogLangLangSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/warm-verse-cache': {
      id: '/api/public/hooks/warm-verse-cache'
      path: '/api/public/hooks/warm-verse-cache'
      fullPath: '/api/public/hooks/warm-verse-cache'
      preLoaderRoute: typeof ApiPublicHooksWarmVerseCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-votd-webhook': {
      id: '/api/public/hooks/daily-votd-webhook'
      path: '/api/public/hooks/daily-votd-webhook'
      fullPath: '/api/public/hooks/daily-votd-webhook'
      preLoaderRoute: typeof ApiPublicHooksDailyVotdWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/commentator-audit': {
      id: '/api/public/hooks/commentator-audit'
      path: '/api/public/hooks/commentator-audit'
      fullPath: '/api/public/hooks/commentator-audit'
      preLoaderRoute: typeof ApiPublicHooksCommentatorAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/new-user-notify': {
      id: '/api/public/admin/new-user-notify'
      path: '/api/public/admin/new-user-notify'
      fullPath: '/api/public/admin/new-user-notify'
      preLoaderRoute: typeof ApiPublicAdminNewUserNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  CopyrightRoute: CopyrightRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  VerseSlugRoute: VerseSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicAdminNewUserNotifyRoute: ApiPublicAdminNewUserNotifyRoute,
  ApiPublicHooksCommentatorAuditRoute: ApiPublicHooksCommentatorAuditRoute,
  ApiPublicHooksDailyVotdWebhookRoute: ApiPublicHooksDailyVotdWebhookRoute,
  ApiPublicHooksWarmVerseCacheRoute: ApiPublicHooksWarmVerseCacheRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  BlogLangLangSlugRoute: BlogLangLangSlugRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  BlogLangLangIndexRoute: BlogLangLangIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
